"""initial_schema

Revision ID: 8014d4e1eb12
Revises:
Create Date: 2026-04-14 17:12:27.443901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8014d4e1eb12"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registered_services",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("upstream_urls", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("rate_limit_override", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_registered_services_id"), "registered_services", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_registered_services_name"),
        "registered_services",
        ["name"],
        unique=True,
    )
    op.create_foreign_key(None, "requests", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "requests", type_="foreignkey")
    op.drop_index(op.f("ix_registered_services_name"), table_name="registered_services")
    op.drop_index(op.f("ix_registered_services_id"), table_name="registered_services")
    op.drop_table("registered_services")
    # ### end Alembic commands ###
